disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Mark's Blog"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "January 2, 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "Technical content and opinions on software"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Mark Bundschuh"
  email = "mark@mbund.dev"
  image = "img/me.jpg"
  imageQuality = 96
  headline = "Computer Science and Engineering Student @ The Ohio State University"
  bio = "An eigenvector is a eigenvalue in the category of endofunctors"
  links = [
    { rss = "/index.xml" },
    { github = "https://github.com/mbund" },
    { linkedin = "https://linkedin.com/in/mark-bundschuh" },
    { bluesky = "https://bsky.app/profile/mbund.dev" },
    { mastodon = "https://mastodon.social/@mbund" },
    { email = "mailto:mark@mbund.dev" },
  ]
